# -*- coding: utf-8 -*-
"""Ful.io_assessment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GcTlxJVfFeMSbBRER6YYwCXitVkjPhRC
"""

pip install requests

import requests
from bs4 import BeautifulSoup
import re

url = 'https://www.w3schools.com'

response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')

links = soup.find_all('a')

for link in links:
    url = link['href']
    if re.search('jquery', url):
        print(f'The link {url} is valid.')

import pandas as pd
import io

from google.colab import files


uploaded = files.upload()

df = pd.read_excel(io.BytesIO(uploaded['Book.xlsx']))
print(df)

l1,l2,l3=df.columns

ans=[]
for i in zip(df[l1],df[l2],df[l3]):
  print("Technology Name :",i[0])
  print('Regex Pattern :',i[1])
  print('sample Website :',i[2])
  print()